### ISSUE TITLE
toc.xhtml issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/bleak-house_charles-dickens#3]
- Chapter should be in a nested wrapping `<ol>` item after the link to the halftitle
- You can remove the `<span epub:type="subtitle">` semantic in the ToC items from this and future productions. I know they were in the ToC template, but we're removing them from the ToC as we slowly progress to automated ToC generation, and since the `subtitle` semantic must occur within a `title` semantic for it to make any sense. This should be a quick find-and-replace, sorry for the extra trouble.

**Comment by drgrigg** [comment]
Done.

**Comment by drgrigg** [comment]
Whoops, didn't pass build. Re-opening.

**Comment by drgrigg** [comment]
Now it should be OK.
